#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

CONFIGURATION="
frontend http_front
	bind *:80
	mode http
	option forwardfor
	stats uri /haproxy?stats
	default_backend http_back
backend http_back
	balance roundrobin
	mode http
	server 84594-web-01 54.236.51.17:80 check
	server 84594-web-02 54.82.137.6:80 check
"

add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get update -y
apt install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
echo "$CONFIGURATION" >> /etc/haproxy/haproxy.cfg
service haproxy start
